name: build

on:
    workflow_dispatch: {}
    schedule:
      - cron:  '0 12 * * *' 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Generate
      run: |
        go get ./...
        make gen

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Load version
      run: echo "TG_BPT_API_VERSION=$(jq -r .version dist/spec/latest.json)" >> $GITHUB_ENV

    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: >
          feat: Update bot API docs to version ${{ env.TG_BPT_API_VERSION }}
        title: >
          Update bot API docs based on the latest changes
        body: >
          This is an automated PR. Please check the diff, and the action logs, to check for any funky behaviour.
        branch: automated/bot-api-update
        reviewers: TBXark
        assignees: TBXark
        labels: automated
        delete-branch: true